const mocks = `/COMMAND.COM
/FRUNLOG.TXT
/WINDOWS
/NETLOG.TXT
/CONFIG.SYS
/AUTOEXEC.BAT
/SCANDISK.LOG
/Program Files
/My Documents
/Windows/SYSTEM
/Windows/WINSOCK.DLL
/Windows/WIN.INI
/Windows/HWINFO.EXE
/Windows/NETDET.INI
/Windows/PIDGEN.DLL
/Windows/SUBACK.BIN
/Windows/W98SETUP.BIN
/Windows/HELP
/Windows/LICENSE.TXT
/Windows/SUPPORT.TXT
/Windows/SYSTEM32
/Windows/MPLAYER.EXE
/Windows/CURSORS
/Windows/RUNHELP.CAB
/Windows/JAVA
/Windows/COMMAND
/Windows/JAUTOEXP.DAT
/Windows/NDDEAPI.DLL
/Windows/NDDENB.DLL
/Windows/SCRIPT.DOC
/Windows/CLSPACK.EXE
/Windows/DOSREP.EXE
/Windows/DRWATSON.EXE
/Windows/EXPLORER.EXE
/Windows/EXTRAC32.EXE
/Windows/FONTVIEW.EXE
/Windows/GRPCONV.EXE
/Windows/HH.EXE
/Windows/JVIEW.EXE
/Windows/MSNMGSR1.EXE
/Windows/NETDDE.EXE
/Windows/PIDSET.EXE
/Windows/SETDEBUG.EXE
/Windows/SIGVERIF.EXE
/Windows/TUNEUP.EXE
/Windows/UPWIZUN.EXE
/Windows/WINREP.EXE
/Windows/WJVIEW.EXE
/Windows/BACKGRND.GIF
/Windows/CLOUD.GIF
/Windows/CONTENT.GIF
/Windows/HLPBELL.GIF
/Windows/HLPCD.GIF
/Windows/HLPGLOBE.GIF
/Windows/HLPLOGO.GIF
/Windows/HLPSTEP1.GIF
/Windows/HLPSTEP2.GIF
/Windows/HLPSTEP3.GIF
/Windows/WINLOGO.GIF
/Windows/DRWATSON
/Windows/HTMLHELP.HTM
/Windows/README.HTM
/Windows/READM_01.HTZ
/Windows/READM_02.HTZ
/Windows/CONFIG
/Windows/DELETEFI.INI
/Windows/DOSREP.INI
/Windows/HTMLHELP.INI
/Windows/MSDFMAP.INI
/Windows/TASKS
/Windows/DOSPRMPT.PIF
/Windows/EXPLORER.SCF
/Windows/ODBCINST.INI
/Windows/CONFIG.TXT
/Windows/DISPLAY.TXT
/Windows/FAQ.TXT
/Windows/GENERAL.TXT
/Windows/HARDWARE.TXT
/Windows/MOUSE.TXT
/Windows/MSDOSDRV.TXT
/Windows/NETWORK.TXT
/Windows/PRINTERS.TXT
/Windows/PROGRAMS.TXT
/Windows/RECOVER.TXT
/Windows/TIPS.TXT
/Windows/MEDIA
/Windows/WSCRIPT.EXE
/Windows/TELEPHON.INI
/Windows/SMARTDRV.EXE
/Windows/HIDCI.DLL
/Windows/CATROOT
/Windows/HIMEM.SYS
/Windows/RAMDRIVE.SYS
/Windows/LOGOS.SYS
/Windows/LOGOW.SYS
/Windows/1STBOOT.BMP
/Windows/Circles.bmp
/Windows/Forest.bmp
/Windows/Metal Links.bmp
/Windows/Pinstripe.bmp
/Windows/SYSTEM.INI
/Windows/Tiles.bmp
/Windows/Setup.bmp
/Windows/WAVEMIX.INI
/Windows/Clouds.bmp
/Windows/POWERPNT.INI
/Windows/WIN.COM
/Windows/CONFDENT.CPE
/Windows/FYI.CPE
/Windows/GENERIC.CPE
/Windows/URGENT.CPE
/Windows/MORICONS.DLL
/Windows/MSOWS409.DLL
/Windows/CTPNP.CFG
/Windows/ACCSTAT.EXE
/Windows/ASD.EXE
/Windows/CALC.EXE
/Windows/CLEANMGR.EXE
/Windows/CONTROL.EXE
/Windows/CVT1.EXE
/Windows/CVTAPLOG.EXE
/Windows/DEFRAG.EXE
/Windows/DRVSPACE.EXE
/Windows/EMM386.EXE
/Windows/MM2ENT.EXE
/Windows/NOTEPAD.EXE
/Windows/PACKAGER.EXE
/Windows/PBRUSH.EXE
/Windows/PROGMAN.EXE
/Windows/REGEDIT.EXE
/Windows/RG2CATDB.EXE
/Windows/RUNDLL.EXE
/Windows/RUNDLL32.EXE
/Windows/SCANDSKW.EXE
/Windows/SCANREGW.EXE
/Windows/SNDREC32.EXE
/Windows/SNDVOL32.EXE
/Windows/TASKMAN.EXE
/Windows/TASKMON.EXE
/Windows/VCMUI.EXE
/Windows/WELCOME.EXE
/Windows/WINFILE.EXE
/Windows/WINHELP.EXE
/Windows/WINHLP32.EXE
/Windows/WININIT.EXE
/Windows/WINVER.EXE
/Windows/WRITE.EXE
/Windows/WUPDMGR.EXE
/Windows/WINUPD.ICO
/Windows/DRVSPACE.INF
/Windows/IOS.INI
/Windows/SCANREG.INI
/Windows/PIF
/Windows/Straw Mat.bmp
/Windows/ASPI2HLP.SYS
/Windows/CMD640X.SYS
/Windows/CMD640X2.SYS
/Windows/DBLBUFF.SYS
/Windows/IFSHLP.SYS
/Windows/SFCSYNC.TXT
/Windows/TWAIN.DLL
/Windows/TWAIN_32.DLL
/Windows/CDPLAYER.EXE
/Windows/DIALER.EXE
/Windows/FREECELL.EXE
/Windows/KODAKIMG.EXE
/Windows/KODAKPRV.EXE
/Windows/MSHEARTS.EXE
/Windows/MSNCREAT.EXE
/Windows/SOL.EXE
/Windows/TOUR98.EXE
/Windows/TWUNK_16.EXE
/Windows/TWUNK_32.EXE
/Windows/WINMINE.EXE
/Windows/SAMPLES
/Windows/SERVICES.TXT
/Windows/COMMAND.COM
/Windows/Default.sf0
/Windows/SETVER.EXE
/Windows/WININIT.BAK
/Windows/QTW.INI
/Windows/NDISLOG.TXT
/Windows/CONTROL.INI
/Windows/TREVOR.PWL
/Windows/MSOFFICE.INI
/Windows/SYSTEM.CB
/Windows/TEMP
/Windows/WIN386.SWP
/Windows/MSIMGSIZ.DAT
/Windows/MODEMDET.TXT
/Windows/PROTOCOL.INI
/Windows/PROTMAN.DOS
/Windows/PROTMAN.EXE
/Windows/NDISHLP.SYS
/Windows/PROTOCOL
/Windows/PCNTND.DOS
/Windows/SERVICES
/Windows/SNMPAPI.DLL
/Windows/NETWORKS
/Windows/ARP.EXE
/Windows/FTP.EXE
/Windows/HOSTS.SAM
/Windows/LMHOSTS.SAM
/Windows/NET.EXE
/Windows/NET.MSG
/Windows/PING.EXE
/Windows/ROUTE.EXE
/Windows/TELNET.EXE
/Windows/TRACERT.EXE
/Windows/WINIPCFG.EXE
/Windows/WINPOPUP.EXE
/Windows/NETH.MSG
/Windows/NETSTAT.EXE
/Windows/IPCONFIG.EXE
/Windows/NBTSTAT.EXE
/Windows/INETMIB1.DLL
/Windows/MS-DOS Mode for Games.pif
/Windows/MS-DOS Mode for Games with EMS and XMS Support.pif
/Windows/Bubbles.bmp
/Windows/Carved Stone.bmp
/Windows/Waves.bmp
/Windows/Houndstooth.bmp
/Windows/Triangles.bmp
/Windows/Blue Rivets.bmp
/Windows/Black Thatch.bmp
/Windows/Red Blocks.bmp
/Windows/Gold Weave.bmp
/Windows/Sandstone.bmp
/Windows/Stitches.bmp
/Windows/Channel Screen Saver.SCR
/Windows/All Users
/Windows/Application Data
/Windows/Desktop
/Windows/Start Menu
/Windows/SendTo
/Windows/progman.ini
/Windows/brndlog.txt
/Windows/Offline Web Pages
/Windows/OEWABLog.txt
/Windows/SchedLog.Txt
/Windows/Default.sfc
/Windows/brndlog.bak
/Windows/command.PIF
/Windows/System/WSOCK32.DLL
/Windows/System/CFGWIZ.DLL
/Windows/System/CFGWIZ32.EXE
/Windows/System/DINDI.DLL
/Windows/System/DLCNDI.DLL
/Windows/System/INFRARED.DLL
/Windows/System/ISSETUP.DLL
/Windows/System/MSTCP.DLL
/Windows/System/NDSWAN16.DLL
/Windows/System/NDSWAN32.DLL
/Windows/System/NETAPI.DLL
/Windows/System/NETDI.DLL
/Windows/System/NETOS.DLL
/Windows/System/NWNDS.DLL
/Windows/System/PPPNDI.DLL
/Windows/System/RNASETUP.DLL
/Windows/System/WAN.TSP
/Windows/System/SVRAPI.DLL
/Windows/System/MSJSTICK.DRV
/Windows/System/SUPERVGA.DRV
/Windows/System/MSMOUSE.VXD
/Windows/System/VJOYD.VXD
/Windows/System/IENPSTUB.DLL
/Windows/System/IPHLPAPI.DLL
/Windows/System/MSLOCUSR.DLL
/Windows/System/RPCLTC1.DLL
/Windows/System/RPCLTC5.DLL
/Windows/System/RPCLTS5.DLL
/Windows/System/SECUR32.DLL
/Windows/System/NDIS.VXD
/Windows/System/NDIS2SUP.VXD
/Windows/System/FRAMEBUF.DLL
/Windows/System/MWCI.DLL
/Windows/System/FRAMEBUF.DRV
/Windows/System/MSANALOG.VXD
/Windows/System/VGAFULL.3GR
/Windows/System/ACELPDEC.AX
/Windows/System/CLRAMD.AX
/Windows/System/IAC25_32.AX
/Windows/System/IR41_32.AX
/Windows/System/IVFSRC.AX
/Windows/System/L3CODECX.AX
/Windows/System/MPG2SPLT.AX
/Windows/System/MPG4DS32.AX
/Windows/System/TM20DEC.AX
/Windows/System/VOXMSDEC.AX
/Windows/System/VOXMVDEC.AX
/Windows/System/VVAUDFLT.AX
/Windows/System/VVVIDFLT.AX
/Windows/System/MIDIMAP.CFG
/Windows/System/DRVVFP.CNT
/Windows/System/MSORCL32.CNT
/Windows/System/ODBCINST.CNT
/Windows/System/ODBCJET.CNT
/Windows/System/DESK.CPL
/Windows/System/INETCPL.CPL
/Windows/System/INTL.CPL
/Windows/System/JOY.CPL
/Windows/System/MMSYS.CPL
/Windows/System/MODEM.CPL
/Windows/System/NETCPL.CPL
/Windows/System/ODBCCP32.CPL
/Windows/System/PASSWORD.CPL
/Windows/System/POWERCFG.CPL
/Windows/System/12520437.CPX
/Windows/System/12520850.CPX
/Windows/System/OOBE
/Windows/System/ACTXPRXY.DLL
/Windows/System/ADVAPI32.DLL
/Windows/System/ADVPACK.DLL
/Windows/System/AMSTREAM.DLL
/Windows/System/ASYCFILT.DLL
/Windows/System/AVICAP.DLL
/Windows/System/AVICAP32.DLL
/Windows/System/AVIFIL32.DLL
/Windows/System/AVIFILE.DLL
/Windows/System/BATMETER.DLL
/Windows/System/BROWSELC.DLL
/Windows/System/BROWSEUI.DLL
/Windows/System/CABINET.DLL
/Windows/System/SHELLEXT
/Windows/System/CCFG95.DLL
/Windows/System/CDFVIEW.DLL
/Windows/System/CDM.DLL
/Windows/System/CFGMGR32.DLL
/Windows/System/CLICONFG.DLL
/Windows/System/CLRVIDDC.DLL
/Windows/System/CMCFG32.DLL
/Windows/System/CMDIAL32.DLL
/Windows/System/CMPBK32.DLL
/Windows/System/CMUTIL.DLL
/Windows/System/CNET16.DLL
/Windows/System/CNETCFG.DLL
/Windows/System/COMCAT.DLL
/Windows/System/COMCTL32.DLL
/Windows/System/COMPOBJ.DLL
/Windows/System/COOL.DLL
/Windows/System/CORPOL.DLL
/Windows/System/CRYPT32.DLL
/Windows/System/CRYPTDLG.DLL
/Windows/System/CRYPTEXT.DLL
/Windows/System/CRYPTNET.DLL
/Windows/System/CRYPTUI.DLL
/Windows/System/D3DIM.DLL
/Windows/System/D3DPMESH.DLL
/Windows/System/D3DRAMP.DLL
/Windows/System/D3DRM.DLL
/Windows/System/D3DXOF.DLL
/Windows/System/DANIM.DLL
/Windows/System/DBMSADSN.DLL
/Windows/System/DBMSRPCN.DLL
/Windows/System/DBMSSHRN.DLL
/Windows/System/DBMSSOCN.DLL
/Windows/System/DBMSSPXN.DLL
/Windows/System/DBMSVINN.DLL
/Windows/System/DBNMPNTW.DLL
/Windows/System/DCIMAN.DLL
/Windows/System/DCIMAN32.DLL
/Windows/System/DDRAW.DLL
/Windows/System/DDRAW16.DLL
/Windows/System/DECVW_32.DLL
/Windows/System/DEVENUM.DLL
/Windows/System/DIGEST.DLL
/Windows/System/DIGSIG.DLL
/Windows/System/DINPUT.DLL
/Windows/System/DISPDIB.DLL
/Windows/System/DISPEX.DLL
/Windows/System/DMBAND.DLL
/Windows/System/DMCOMPOS.DLL
/Windows/System/DMIME.DLL
/Windows/System/DMLOADER.DLL
/Windows/System/DMSTYLE.DLL
/Windows/System/DMSYNTH.DLL
/Windows/System/DMUSIC.DLL
/Windows/System/DMUSIC16.DLL
/Windows/System/DMUSIC32.DLL
/Windows/System/DPLAY.DLL
/Windows/System/DPLAYX.DLL
/Windows/System/DPMODEMX.DLL
/Windows/System/DPSERIAL.DLL
/Windows/System/DPWSOCK.DLL
/Windows/System/DPWSOCKX.DLL
/Windows/System/DS16GT.DLL
/Windows/System/DS32GT.DLL
/Windows/System/DSOUND.DLL
/Windows/System/DSOUND3D.DLL
/Windows/System/DSSBASE.DLL
/Windows/System/DX3J.DLL
/Windows/System/DXMASF.DLL
/Windows/System/DXTMSFT.DLL
/Windows/System/DXTMSFT3.DLL
/Windows/System/DXTRANS.DLL
/Windows/System/ENHSIG.DLL
/Windows/System/ES.DLL
/Windows/System/ESENU.DLL
/Windows/System/ESSHARED.DLL
/Windows/System/ESTIER2.DLL
/Windows/System/EXPSRV.DLL
/Windows/System/FONTEXT.DLL
/Windows/System/GCDEF.DLL
/Windows/System/GCHAND.DLL
/Windows/System/HLINK.DLL
/Windows/System/HWAGENT.DLL
/Windows/System/ICFG95.DLL
/Windows/System/ICWDIAL.DLL
/Windows/System/ICWPHBK.DLL
/Windows/System/IEDKCS32.DLL
/Windows/System/IEPEERS.DLL
/Windows/System/IERNONCE.DLL
/Windows/System/IESETUP.DLL
/Windows/System/IMAGEHLP.DLL
/Windows/System/IMGUTIL.DLL
/Windows/System/INDICDLL.DLL
/Windows/System/INET16.DLL
/Windows/System/INETCFG.DLL
/Windows/System/INETCPLC.DLL
/Windows/System/INITPKI.DLL
/Windows/System/INSENG.DLL
/Windows/System/INSTRSA.DLL
/Windows/System/IPROP.DLL
/Windows/System/IR41_QC.DLL
/Windows/System/IR41_QCX.DLL
/Windows/System/IR50_32.DLL
/Windows/System/IR50_QC.DLL
/Windows/System/IR50_QCX.DLL
/Windows/System/IR_NDI.DLL
/Windows/System/ISIGN32.DLL
/Windows/System/ITIRCL.DLL
/Windows/System/ITSS.DLL
/Windows/System/JAVACYPT.DLL
/Windows/System/JAVAEE.DLL
/Windows/System/JAVAPRXY.DLL
/Windows/System/JAVART.DLL
/Windows/System/JGAW400.DLL
/Windows/System/JGDW400.DLL
/Windows/System/JGMD400.DLL
/Windows/System/JGPL400.DLL
/Windows/System/JGSD400.DLL
/Windows/System/JGSH400.DLL
/Windows/System/JIT.DLL
/Windows/System/JOBEXEC.DLL
/Windows/System/JSCRIPT.DLL
/Windows/System/JSPROXY.DLL
/Windows/System/LICMGR10.DLL
/Windows/System/LMRT.DLL
/Windows/System/LMRTREND.DLL
/Windows/System/MBSLGN32.DLL
/Windows/System/MCIOLE.DLL
/Windows/System/MCIQTZ32.DLL
/Windows/System/MEMBG.DLL
/Windows/System/MFCUIA32.DLL
/Windows/System/MFCUIW32.DLL
/Windows/System/MLANG.DLL
/Windows/System/MMCI.DLL
/Windows/System/MMSYSTEM.DLL
/Windows/System/MMUTILSE.DLL
/Windows/System/MOBSYNC.DLL
/Windows/System/MPR.DLL
/Windows/System/MPRSERV.DLL
/Windows/System/MSACM.DLL
/Windows/System/MSACM32.DLL
/Windows/System/MSAPSSPC.DLL
/Windows/System/MSAWT.DLL
/Windows/System/MSCAT32.DLL
/Windows/System/MSCPXL32.DLL
/Windows/System/MSENCODE.DLL
/Windows/System/MSEXCH40.DLL
/Windows/System/MSEXCL40.DLL
/Windows/System/MSHTML.DLL
/Windows/System/MSHTMLED.DLL
/Windows/System/MSHTMLER.DLL
/Windows/System/MSIDENT.DLL
/Windows/System/MSIDLE.DLL
/Windows/System/MSIDNTLD.DLL
/Windows/System/MSIEFTP.DLL
/Windows/System/MSJAVA.DLL
/Windows/System/MSJDBC10.DLL
/Windows/System/MSJET35.DLL
/Windows/System/MSJET40.DLL
/Windows/System/MSJINT40.DLL
/Windows/System/MSJT3032.DLL
/Windows/System/MSJTER40.DLL
/Windows/System/MSJTES40.DLL
/Windows/System/MSLS31.DLL
/Windows/System/MSLTUS40.DLL
/Windows/System/MSMIXMGR.DLL
/Windows/System/MSNSSPC.DLL
/Windows/System/MSORCL32.DLL
/Windows/System/MSOSS.DLL
/Windows/System/MSPBDE40.DLL
/Windows/System/MSPWL32.DLL
/Windows/System/MSRATING.DLL
/Windows/System/MSRCLR40.DLL
/Windows/System/MSRD2X40.DLL
/Windows/System/MSRD3X40.DLL
/Windows/System/MSRECR40.DLL
/Windows/System/MSREPL35.DLL
/Windows/System/MSREPL40.DLL
/Windows/System/MSSIGN32.DLL
/Windows/System/MSSIP32.DLL
/Windows/System/MSTASK.DLL
/Windows/System/MSTEXT40.DLL
/Windows/System/MSVFW32.DLL
/Windows/System/MSVIDEO.DLL
/Windows/System/MSWDAT10.DLL
/Windows/System/MSWSTR10.DLL
/Windows/System/MSXBDE40.DLL
/Windows/System/MSXML.DLL
/Windows/System/MTXDM.DLL
/Windows/System/MTXOCI.DLL
/Windows/System/NETAPI32.DLL
/Windows/System/NETBIOS.DLL
/Windows/System/OCCACHE.DLL
/Windows/System/ODBC16GT.DLL
/Windows/System/ODBC32.DLL
/Windows/System/ODBC32GT.DLL
/Windows/System/ODBCBCP.DLL
/Windows/System/ODBCCP32.DLL
/Windows/System/ODBCCR32.DLL
/Windows/System/ODBCCU32.DLL
/Windows/System/ODBCINT.DLL
/Windows/System/ODBCJI32.DLL
/Windows/System/ODBCJT32.DLL
/Windows/System/ODBCTRAC.DLL
/Windows/System/ODDBSE32.DLL
/Windows/System/ODEXL32.DLL
/Windows/System/ODFOX32.DLL
/Windows/System/ODPDX32.DLL
/Windows/System/ODTEXT32.DLL
/Windows/System/OLE2.DLL
/Windows/System/OLE2CONV.DLL
/Windows/System/OLE2DISP.DLL
/Windows/System/OLE2NLS.DLL
/Windows/System/OLE32.DLL
/Windows/System/OLEACC.DLL
/Windows/System/OLEACCRC.DLL
/Windows/System/OLEAUT32.DLL
/Windows/System/OLECNV32.DLL
/Windows/System/OLEDLG.DLL
/Windows/System/OLETHK32.DLL
/Windows/System/PANMAP.DLL
/Windows/System/PID.DLL
/Windows/System/PLUSTAB.DLL
/Windows/System/PNGFILT.DLL
/Windows/System/POWRPROF.DLL
/Windows/System/PSBASE.DLL
/Windows/System/PSTOREC.DLL
/Windows/System/PSTORERC.DLL
/Windows/System/QCAP.DLL
/Windows/System/QCUT.DLL
/Windows/System/QDV.DLL
/Windows/System/QDVD.DLL
/Windows/System/QUARTZ.DLL
/Windows/System/RASAPI32.DLL
/Windows/System/RICHED32.DLL
/Windows/System/RNAPH.DLL
/Windows/System/RPCLTCCM.DLL
/Windows/System/RPCLTSCM.DLL
/Windows/System/RPCLTSPX.DLL
/Windows/System/RPCMQCL.DLL
/Windows/System/RPCMQSVR.DLL
/Windows/System/RPCNS4.DLL
/Windows/System/RPCRT4.DLL
/Windows/System/RSABASE.DLL
/Windows/System/RSASIG.DLL
/Windows/System/SAGE.DLL
/Windows/System/SCROBJ.DLL
/Windows/System/SENDMAIL.DLL
/Windows/System/SENS.DLL
/Windows/System/SENSAPI.DLL
/Windows/System/SENSCFG.DLL
/Windows/System/SETUPAPI.DLL
/Windows/System/SETUPWBV.DLL
/Windows/System/SHD401LC.DLL
/Windows/System/SHDOC401.DLL
/Windows/System/SHDOCLC.DLL
/Windows/System/SHDOCVW.DLL
/Windows/System/SHELL32.DLL
/Windows/System/SHFOLDER.DLL
/Windows/System/SHLWAPI.DLL
/Windows/System/SOFTPUB.DLL
/Windows/System/SQLSRV32.DLL
/Windows/System/SQLSTR.DLL
/Windows/System/SQLWID.DLL
/Windows/System/SQLWOA.DLL
/Windows/System/STORAGE.DLL
/Windows/System/STRMDLL.DLL
/Windows/System/SYNCENG.DLL
/Windows/System/T2EMBED.DLL
/Windows/System/THUMBVW.DLL
/Windows/System/TYPELIB.DLL
/Windows/System/URL.DLL
/Windows/System/URLMON.DLL
/Windows/System/VBAJET32.DLL
/Windows/System/VBSCRIPT.DLL
/Windows/System/VDODEC32.DLL
/Windows/System/VFPODBC.DLL
/Windows/System/VIDX16.DLL
/Windows/System/VMHELPER.DLL
/Windows/System/W95INF16.DLL
/Windows/System/W95INF32.DLL
/Windows/System/WEBCHECK.DLL
/Windows/System/WEBVW.DLL
/Windows/System/WININET.DLL
/Windows/System/WINMM.DLL
/Windows/System/WINNET16.DLL
/Windows/System/WINTRUST.DLL
/Windows/System/XENROLL.DLL
/Windows/System/KEYBOARD.DRV
/Windows/System/MCIAVI.DRV
/Windows/System/MCICDA.DRV
/Windows/System/MCIQTZ.DRV
/Windows/System/MCISEQ.DRV
/Windows/System/MCIWAVE.DRV
/Windows/System/MIDIMAP.DRV
/Windows/System/MSACM.DRV
/Windows/System/SYSTEM.DRV
/Windows/System/VDOWAVE.DRV
/Windows/System/VGA.DRV
/Windows/System/ACTMOVIE.EXE
/Windows/System/ADDREG.EXE
/Windows/System/CLICONFG.EXE
/Windows/System/CMDL32.EXE
/Windows/System/CMMGR32.EXE
/Windows/System/CMMON32.EXE
/Windows/System/CMSTP.EXE
/Windows/System/DDHELP.EXE
/Windows/System/DLLHOST.EXE
/Windows/System/DPLAYSVR.EXE
/Windows/System/DSSSIG.EXE
/Windows/System/DXDIAG.EXE
/Windows/System/ESSERVER.EXE
/Windows/System/FONTREG.EXE
/Windows/System/ICWSCRPT.EXE
/Windows/System/IE4UINIT.EXE
/Windows/System/IESHWIZ.EXE
/Windows/System/INTERNAT.EXE
/Windows/System/JDBGMGR.EXE
/Windows/System/LIGHTS.EXE
/Windows/System/LOADWC.EXE
/Windows/System/MOBSYNC.EXE
/Windows/System/MPREXE.EXE
/Windows/System/MSHTA.EXE
/Windows/System/MSTASK.EXE
/Windows/System/MSTINIT.EXE
/Windows/System/ODBCAD32.EXE
/Windows/System/ODBCCONF.EXE
/Windows/System/PSTORES.EXE
/Windows/System/REDIR32.EXE
/Windows/System/REGSVR32.EXE
/Windows/System/RPCSS.EXE
/Windows/System/SAGE.EXE
/Windows/System/UNAM4IE.EXE
/Windows/System/CLICONF.HLP
/Windows/System/CMMGR32.HLP
/Windows/System/DRVVFP.HLP
/Windows/System/JAVAPERM.HLP
/Windows/System/JAVASEC.HLP
/Windows/System/MSORCL32.HLP
/Windows/System/ODBCINST.HLP
/Windows/System/ODBCJET.HLP
/Windows/System/SQLSODBC.HLP
/Windows/System/MEMBG.HTM
/Windows/System/COLOR
/Windows/System/HOMEPAGE.INF
/Windows/System/IE4UINIT.INF
/Windows/System/IEUINIT.INF
/Windows/System/INSTCM.INF
/Windows/System/KBDUS.KBD
/Windows/System/CERTMGR.MSC
/Windows/System/CP_1250.NLS
/Windows/System/CP_1251.NLS
/Windows/System/CP_1252.NLS
/Windows/System/CP_1253.NLS
/Windows/System/CP_1254.NLS
/Windows/System/CP_1257.NLS
/Windows/System/CP_20866.NLS
/Windows/System/CP_28591.NLS
/Windows/System/CP_28592.NLS
/Windows/System/CP_28595.NLS
/Windows/System/CP_28597.NLS
/Windows/System/CP_437.NLS
/Windows/System/CP_737.NLS
/Windows/System/CP_775.NLS
/Windows/System/CP_850.NLS
/Windows/System/CP_852.NLS
/Windows/System/CP_855.NLS
/Windows/System/CP_857.NLS
/Windows/System/CP_866.NLS
/Windows/System/CP_869.NLS
/Windows/System/LOCALE.NLS
/Windows/System/UNICODE.NLS
/Windows/System/AMOVIE.OCX
/Windows/System/ASCTRLS.OCX
/Windows/System/BR549.OCX
/Windows/System/EYEDOG.OCX
/Windows/System/HHCTRL.OCX
/Windows/System/MMEFXE.OCX
/Windows/System/MSDXM.OCX
/Windows/System/PLUGIN.OCX
/Windows/System/PROCTEXE.OCX
/Windows/System/RSACI.RAT
/Windows/System/ODBCCONF.RSP
/Windows/System/INSTCAT.SQL
/Windows/System/DXAPI.SYS
/Windows/System/MSDATSRC.TLB
/Windows/System/MSHTML.TLB
/Windows/System/SIMPDATA.TLB
/Windows/System/STDOLE.TLB
/Windows/System/STDOLE2.TLB
/Windows/System/STDOLE32.TLB
/Windows/System/MMTASK.TSK
/Windows/System/SQLSRDME.TXT
/Windows/System/VFPODBC.TXT
/Windows/System/MSMS001.VWP
/Windows/System/MVOICED.VWP
/Windows/System/DDRAW.VXD
/Windows/System/DINPUT.VXD
/Windows/System/DSOUND.VXD
/Windows/System/JAVASUP.VXD
/Windows/System/LOGGER.VXD
/Windows/System/MMDEVLDR.VXD
/Windows/System/MSGAME.VXD
/Windows/System/PARALINK.VXD
/Windows/System/QUARTZ.VXD
/Windows/System/SAGE.VXD
/Windows/System/SW3DPRO.VXD
/Windows/System/SW3DPRO2.VXD
/Windows/System/SWGAMPAD.VXD
/Windows/System/VMM32
/Windows/System/LHACM.ACM
/Windows/System/DDRAWEX.DLL
/Windows/System/MFC42.DLL
/Windows/System/MODEMUI.DLL
/Windows/System/MSVCRT.DLL
/Windows/System/OLEPRO32.DLL
/Windows/System/SCRRUN.DLL
/Windows/System/UMDM16.DLL
/Windows/System/UMDM32.DLL
/Windows/System/UMDMXFRM.DLL
/Windows/System/VMODCTL.DLL
/Windows/System/WLDAP32.DLL
/Windows/System/WSHEXT.DLL
/Windows/System/SERWVDRV.DRV
/Windows/System/WAVEWRAP.DRV
/Windows/System/WSHOM.OCX
/Windows/System/UNIMDM.TSP
/Windows/System/SERWAVE.VXD
/Windows/System/UNIMODEM.VXD
/Windows/System/DSKMAINT.DLL
/Windows/System/COMMCTRL.DLL
/Windows/System/LZEXPAND.DLL
/Windows/System/MINI.CAB
/Windows/System/MSPRINT.DLL
/Windows/System/MSPRINT2.DLL
/Windows/System/SYSDETMG.DLL
/Windows/System/HIDCI.DLL
/Windows/System/SUCATREG.EXE
/Windows/System/SETUPX.DLL
/Windows/System/SERIALUI.DLL
/Windows/System/LPT.VXD
/Windows/System/SERIAL.VXD
/Windows/System/WDMMDMLD.VXD
/Windows/System/MSSHRUI.DLL
/Windows/System/MSWSOCK.DLL
/Windows/System/MSWSOSP.DLL
/Windows/System/WS2_32.DLL
/Windows/System/WS2HELP.DLL
/Windows/System/WS2THK.DLL
/Windows/System/WSCTHUNK.DLL
/Windows/System/WSASRV.EXE
/Windows/System/FILESEC.VXD
/Windows/System/PPPMAC.VXD
/Windows/System/WSOCK.VXD
/Windows/System/WSOCK2.VXD
/Windows/System/KSUSER.DLL
/Windows/System/WDMAUD.DRV
/Windows/System/THREED.VBX
/Windows/System/VRTWD.386
/Windows/System/IMAADP32.ACM
/Windows/System/MSADP32.ACM
/Windows/System/MSGSM32.ACM
/Windows/System/TSSOFT32.ACM
/Windows/System/OEMREG.BIN
/Windows/System/UNICODE.BIN
/Windows/System/ACCESS.CPL
/Windows/System/APPWIZ.CPL
/Windows/System/MAIN.CPL
/Windows/System/STICPL.CPL
/Windows/System/SYSDM.CPL
/Windows/System/TELEPHON.CPL
/Windows/System/TIMEDATE.CPL
/Windows/System/ACCTRES.DLL
/Windows/System/CLUSALGO.DLL
/Windows/System/COMDLG32.DLL
/Windows/System/CRTDLL.DLL
/Windows/System/CTL3D.DLL
/Windows/System/CTL3D32.DLL
/Windows/System/CTL3DV2.DLL
/Windows/System/CVT16.DLL
/Windows/System/CVT32.DLL
/Windows/System/DATACLEN.DLL
/Windows/System/DDEML.DLL
/Windows/System/DESKCP16.DLL
/Windows/System/DEVMGR32.DLL
/Windows/System/DIBENG.DLL
/Windows/System/MACROMED
/Windows/System/DISKCOPY.DLL
/Windows/System/DOCPROP.DLL
/Windows/System/ENABLE3.DLL
/Windows/System/ENUMFILE.DLL
/Windows/System/FTSRCH.DLL
/Windows/System/GDI32.DLL
/Windows/System/GLU32.DLL
/Windows/System/HID.DLL
/Windows/System/ICCVID.DLL
/Windows/System/ICM32.DLL
/Windows/System/ICMUI.DLL
/Windows/System/ICMUPG.DLL
/Windows/System/IMM32.DLL
/Windows/System/INETCOMM.DLL
/Windows/System/INETRES.DLL
/Windows/System/IOSCLASS.DLL
/Windows/System/IR32_32.DLL
/Windows/System/KERNEL32.DLL
/Windows/System/LINKINFO.DLL
/Windows/System/LZ32.DLL
/Windows/System/MAINCP16.DLL
/Windows/System/MAPISTUB.DLL
/Windows/System/MF3216.DLL
/Windows/System/MFC30.DLL
/Windows/System/MFC40.DLL
/Windows/System/MFCANS32.DLL
/Windows/System/MFCD30.DLL
/Windows/System/MFCN30.DLL
/Windows/System/MFCO30.DLL
/Windows/System/MSCMS.DLL
/Windows/System/MSIMG32.DLL
/Windows/System/MSOEACCT.DLL
/Windows/System/MSOERT2.DLL
/Windows/System/MSPCIC.DLL
/Windows/System/MSR2C.DLL
/Windows/System/MSR2CENU.DLL
/Windows/System/MSRLE32.DLL
/Windows/System/MSVBVM50.DLL
/Windows/System/MSVCRT20.DLL
/Windows/System/MSVCRT40.DLL
/Windows/System/MSVIDC32.DLL
/Windows/System/MYDOCS.DLL
/Windows/System/NTDLL.DLL
/Windows/System/OEMREG.DLL
/Windows/System/OLECLI.DLL
/Windows/System/OLECLI32.DLL
/Windows/System/OLESVR.DLL
/Windows/System/OLESVR32.DLL
/Windows/System/OPENGL32.DLL
/Windows/System/PIFMGR.DLL
/Windows/System/PKPD.DLL
/Windows/System/PKPD32.DLL
/Windows/System/POWEROLD.DLL
/Windows/System/RASAPI16.DLL
/Windows/System/REGWIZC.DLL
/Windows/System/RICHED.DLL
/Windows/System/RICHED20.DLL
/Windows/System/RNANP.DLL
/Windows/System/RNASMM.DLL
/Windows/System/RNATHUNK.DLL
/Windows/System/RNAUI.DLL
/Windows/System/SETUP4.DLL
/Windows/System/SFCDLL.DLL
/Windows/System/SHSCRAP.DLL
/Windows/System/SMMSCRPT.DLL
/Windows/System/SMMSETUP.DLL
/Windows/System/SPOOLSS.DLL
/Windows/System/STEM0409.DLL
/Windows/System/STI.DLL
/Windows/System/STI_CI.DLL
/Windows/System/STI_CI32.DLL
/Windows/System/SYNCUI.DLL
/Windows/System/SYSCLASS.DLL
/Windows/System/SYSINV.DLL
/Windows/System/SYSTHUNK.DLL
/Windows/System/TAPI.DLL
/Windows/System/TAPI32.DLL
/Windows/System/TAPIUI.DLL
/Windows/System/TMAPI.DLL
/Windows/System/TOOLHELP.DLL
/Windows/System/TSD32.DLL
/Windows/System/TSP3216S.DLL
/Windows/System/USER32.DLL
/Windows/System/USP10.DLL
/Windows/System/VDMDBG.DLL
/Windows/System/VERSION.DLL
/Windows/System/WHLP16T.DLL
/Windows/System/WHLP32T.DLL
/Windows/System/WIN32S16.DLL
/Windows/System/WIN87EM.DLL
/Windows/System/WINALIGN.DLL
/Windows/System/WINASPI.DLL
/Windows/System/WMI.DLL
/Windows/System/WMICORE.DLL
/Windows/System/WNASPI32.DLL
/Windows/System/WOW32.DLL
/Windows/System/WUPDINFO.DLL
/Windows/System/IOSUBSYS
/Windows/System/COMM.DRV
/Windows/System/MMSOUND.DRV
/Windows/System/WINSPL16.DRV
/Windows/System/WINSPOOL.DRV
/Windows/System/CONAGENT.EXE
/Windows/System/FIXMAPI.EXE
/Windows/System/GDI.EXE
/Windows/System/IMGSTART.EXE
/Windows/System/KRNL386.EXE
/Windows/System/MKCOMPAT.EXE
/Windows/System/MSCONFIG.EXE
/Windows/System/MSGSRV32.EXE
/Windows/System/REGWIZ.EXE
/Windows/System/RNAAPP.EXE
/Windows/System/RUNONCE.EXE
/Windows/System/SFC.EXE
/Windows/System/SPOOL32.EXE
/Windows/System/STIMON.EXE
/Windows/System/SYSEDIT.EXE
/Windows/System/SYSTRAY.EXE
/Windows/System/TAPI16.EXE
/Windows/System/TAPIINI.EXE
/Windows/System/TAPISRV.EXE
/Windows/System/TAPIUPR.EXE
/Windows/System/TCMSETUP.EXE
/Windows/System/TLOCMGR.EXE
/Windows/System/USER.EXE
/Windows/System/WALIGN.EXE
/Windows/System/WMIEXE.EXE
/Windows/System/CONTROL.INF
/Windows/System/IMGST_TR.INI
/Windows/System/IMGSTART.INI
/Windows/System/WINALI.INI
/Windows/System/WINALX.INI
/Windows/System/CONLOCK.MOD
/Windows/System/REDIRECT.MOD
/Windows/System/COMMDLG.DLL
/Windows/System/SHELL.DLL
/Windows/System/VER.DLL
/Windows/System/WINOA386.MOD
/Windows/System/TDC.OCX
/Windows/System/schannel.dll
/Windows/System/Blank Screen.scr
/Windows/System/Mystify Your Mind.scr
/Windows/System/REMOTESP.TSP
/Windows/System/TSP3216L.TSP
/Windows/System/ENABLE2.VXD
/Windows/System/ENABLE4.VXD
/Windows/System/FIOLOG.VXD
/Windows/System/LPTENUM.VXD
/Windows/System/SERENUM.VXD
/Windows/System/SMARTVSD.VXD
/Windows/System/SPAP.VXD
/Windows/System/SPLITTER.VXD
/Windows/System/VFD.VXD
/Windows/System/VFIXD.VXD
/Windows/System/VGATEWAY.VXD
/Windows/System/PCI.VXD
/Windows/System/SPBANNER.WMF
/Windows/System/MSG711.ACM
/Windows/System/MSG723.ACM
/Windows/System/AWCODC32.DLL
/Windows/System/AWDCXC32.DLL
/Windows/System/AWDENC32.DLL
/Windows/System/AWKRNL32.DLL
/Windows/System/AWRESX32.DLL
/Windows/System/AWVIEW32.DLL
/Windows/System/CARDS.DLL
/Windows/System/DATIME.DLL
/Windows/System/DDAO35.DLL
/Windows/System/DSKAPI16.DLL
/Windows/System/DSKAPI32.DLL
/Windows/System/ILS.DLL
/Windows/System/IMGCMN.DLL
/Windows/System/IMGSHL.DLL
/Windows/System/JPEG1X32.DLL
/Windows/System/JPEG2X32.DLL
/Windows/System/MSASN1.DLL
/Windows/System/MSCONF.DLL
/Windows/System/MSVCIRT.DLL
/Windows/System/NMMKCERT.DLL
/Windows/System/OIADM400.DLL
/Windows/System/OICOM400.DLL
/Windows/System/OIDIS400.DLL
/Windows/System/OIFIL400.DLL
/Windows/System/OIGFS400.DLL
/Windows/System/OIPRT400.DLL
/Windows/System/OISLB400.DLL
/Windows/System/OISSQ400.DLL
/Windows/System/OITWA400.DLL
/Windows/System/OIUI400.DLL
/Windows/System/XFILEXR.DLL
/Windows/System/MCIPIONR.DRV
/Windows/System/MCIVISCA.DRV
/Windows/System/MSH261.DRV
/Windows/System/MSH263.DRV
/Windows/System/AWFXEX32.EXE
/Windows/System/BPCPOST.EXE
/Windows/System/MNMSRVC.EXE
/Windows/System/DAXCTLE.OCX
/Windows/System/HHOPEN.OCX
/Windows/System/IMGADMIN.OCX
/Windows/System/IMGEDIT.OCX
/Windows/System/IMGSCAN.OCX
/Windows/System/IMGTHUMB.OCX
/Windows/System/DCAPVXD.VXD
/Windows/System/STREAMCI.DLL
/Windows/System/VMM32.VXD
/Windows/System/VPOWERD.VXD
/Windows/System/PCIMP.PCI
/Windows/System/ISAPNP.VXD
/Windows/System/USBUI.DLL
/Windows/System/MOUSE.DRV
/Windows/System/POWER.DRV
/Windows/System/NDISWMI.SYS
/Windows/System/VNETBIOS.VXD
/Windows/System/WFM0200.ACV
/Windows/System/WFM0201.ACV
/Windows/System/WFM0202.ACV
/Windows/System/WFM0203.ACV
/Windows/System/WFM0200A.CSP
/Windows/System/WFM0201A.CSP
/Windows/System/WFM0202A.CSP
/Windows/System/WFM0203A.CSP
/Windows/System/CSPMAN.DLL
/Windows/System/SB16SND.DRV
/Windows/System/SBFM.DRV
/Windows/System/SB16.VXD
/Windows/System/VIP.386
/Windows/System/PCNTN4M.SYS
/Windows/System/VLB32.DLL
/Windows/System/VTCP.386
/Windows/System/VTDI.386
/Windows/System/VUDP.386
/Windows/System/LMSCRIPT.EXE
/Windows/System/DHCPCSVC.DLL
/Windows/System/ICMP.DLL
/Windows/System/IPCFGDLL.DLL
/Windows/System/MSAB32.DLL
/Windows/System/MSAFD.DLL
/Windows/System/MSNET32.DLL
/Windows/System/MSNP32.DLL
/Windows/System/MSPP32.DLL
/Windows/System/PMSPL.DLL
/Windows/System/QOSNAME.DLL
/Windows/System/RAPILIB.DLL
/Windows/System/RNR20.DLL
/Windows/System/ROUTETAB.DLL
/Windows/System/RPCLTC3.DLL
/Windows/System/RPCLTS3.DLL
/Windows/System/RSVPSP.DLL
/Windows/System/VDHCP.386
/Windows/System/VNBT.386
/Windows/System/LMSCRIPT.PIF
/Windows/System/LOCPROXY.EXE
/Windows/System/LOCPRXY2.EXE
/Windows/System/RSVP.EXE
/Windows/System/TELNET.HLP
/Windows/System/AFVXD.VXD
/Windows/System/DFS.VXD
/Windows/System/MSSP.VXD
/Windows/System/VNETSUP.VXD
/Windows/System/VREDIR.VXD
/Windows/System/WSHTCP.VXD
/Windows/System/ICMFILTER.DLL
/Windows/System/3D Maze.scr
/Windows/System/CHOOSUSR.DLL
/Windows/System/Show Desktop.scf
/Windows/System/msjetoledb40.dll
/Windows/System/MSOracle32Readme.txt
/Windows/System/Flying Windows.scr
/Windows/System/3D Flying Objects.scr
/Windows/System/3D Pipes.scr
/Windows/System/3D Text.scr
/Windows/System/3D Flower Box.scr
/Windows/System/Flying Through Space.scr
/Windows/System/Curves and Colors.scr
/Windows/System/Scrolling Marquee.scr
/Windows/System/mapi32x.dll
/Windows/System/mapi32.dll
/Windows/System/HwInfoD.vxd
/Windows/System/nscompat.tlb
/Windows/System/amcompat.tlb
/Windows/System/CatRoot
/Program Files/Common Files
/Program Files/CHAT
/Program Files/PLUS!
/Program Files/Online Services
/Program Files/Accessories
/Program Files/Internet Explorer
/Program Files/NetMeeting
/Program Files/Outlook Express
/Program Files/Windows Media Player
/Program Files/Uninstall Information
/Program Files/DirectX
/Program Files/Oracle
`
  .split("\n")
  .filter(Boolean);

export default mocks;
